baseURL = "https://tuequan.org/new/"
title = "Tuệ Quán Thiền Viện"

[params]
  defaultLanguage = "vi"
  description = "Tuệ Quán Thiền Viện — Vipassanā Meditation Center"
  
  templeName = "Tuệ Quán Thiền Viện"
  templeNameEn = "Tuệ Quán Thiền Viện"
  
  address = "3922 W 5th Street, Santa Ana CA 92703"
  addressEn = "3922 W 5th Street, Santa Ana CA 92703"
  
  phone = "(657) 663-0543"
  email = "tuequan.info@gmail.com"
  
  facebook = "https://www.facebook.com/profile.php?id=100093154143454"
  youtube = ""
[taxonomies]
